version: "3.8"
services:
  api:
    build: ./api
    restart: always
    image: yet-another-api-image
    container_name: yet-another-api
    ports:
      - "8009:8009"
    networks:
      database: null
    volumes:
      - ./logs:/yet-another-api/logs
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-}
      DATABASE_PORT: ${DATABASE_PORT:-}
      POSTGRES_USER: ${POSTGRES_USER:-}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      POSTGRES_DB: ${POSTGRES_DB:-}

  postgres:
    image: postgres:alpine
    restart: always
    container_name: yet-another-postgres
    networks:
      database:
        aliases:
          - ${DATABASE_HOST:-}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      POSTGRES_DB: ${POSTGRES_DB:-}
      DATABASE_HOST: ${DATABASE_HOST:-}
      DATABASE_PORT: ${DATABASE_PORT:-}
      
    volumes:
      - ./data/db/:/var/lib/mysql

networks:
  database:
    ipam:
      config:
        - subnet: 216.0.0.0/24
